### ISSUE TITLE
Unable to expand view in iOS

### ISSUE THREAD

**Issue by jagadishcc** [naoufal/react-native-accordion#44]
Your sample code works well in Android. But, It does not work in iOS. It load the list, When taps on it, it does not expand in iOS. I am using Xcode 8 and iOS 10 simulator to test it.

**Comment by doublethug** [comment]
Any ideas how it could be fixed? Having the same problem(((

**Comment by jagadishcc** [comment]
Content height always shows 0. I think content is not rendering in iOS. Please look into this.

**Comment by huyta** [comment]
Maybe this will help https://github.com/naoufal/react-native-accordion/issues/41

**Comment by rajnikantsethiya** [comment]
is there any fix for this issue?

**Comment by dayhaysoos** [comment]
@rajnikantsethiya  I just fixed this by upgrading React Native and applying the fix that @huyta provided

**Comment by iuraya** [comment]
The fix proposed by @jagadishcc is not compatible with Android

**Comment by johnhaup** [comment]
For anyone still having this issue, I switched to the Accordion from the [React-Native-Collapsible](https://github.com/oblador/react-native-collapsible) library.  There was minimal code change from the code I had written with this library and I had no issues on Android iOS.
